<?php
/**
 * MultiSKUPriceAndStockResponseServiceresponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * MultiSKUPriceAndStockResponseServiceresponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MultiSKUPriceAndStockResponseServiceresponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'multiSKUPriceAndStockResponse_serviceresponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'responsepreamble' => '\Swagger\Client\Model\MultiSKUPriceAndStockResponseServiceresponseResponsepreamble',
'priceandstockresponse' => '\Swagger\Client\Model\MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponse'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'responsepreamble' => null,
'priceandstockresponse' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'responsepreamble' => 'responsepreamble',
'priceandstockresponse' => 'priceandstockresponse'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'responsepreamble' => 'setResponsepreamble',
'priceandstockresponse' => 'setPriceandstockresponse'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'responsepreamble' => 'getResponsepreamble',
'priceandstockresponse' => 'getPriceandstockresponse'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['responsepreamble'] = isset($data['responsepreamble']) ? $data['responsepreamble'] : null;
        $this->container['priceandstockresponse'] = isset($data['priceandstockresponse']) ? $data['priceandstockresponse'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets responsepreamble
     *
     * @return \Swagger\Client\Model\MultiSKUPriceAndStockResponseServiceresponseResponsepreamble
     */
    public function getResponsepreamble()
    {
        return $this->container['responsepreamble'];
    }

    /**
     * Sets responsepreamble
     *
     * @param \Swagger\Client\Model\MultiSKUPriceAndStockResponseServiceresponseResponsepreamble $responsepreamble responsepreamble
     *
     * @return $this
     */
    public function setResponsepreamble($responsepreamble)
    {
        $this->container['responsepreamble'] = $responsepreamble;

        return $this;
    }

    /**
     * Gets priceandstockresponse
     *
     * @return \Swagger\Client\Model\MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponse
     */
    public function getPriceandstockresponse()
    {
        return $this->container['priceandstockresponse'];
    }

    /**
     * Sets priceandstockresponse
     *
     * @param \Swagger\Client\Model\MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponse $priceandstockresponse priceandstockresponse
     *
     * @return $this
     */
    public function setPriceandstockresponse($priceandstockresponse)
    {
        $this->container['priceandstockresponse'] = $priceandstockresponse;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
