<?php
/**
 * MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItem Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MultiSKUPriceAndStockAPI_v4_0_Service_vs0_servicerequest_priceandstockrequest_item';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'index' => 'int',
'ingrampartnumber' => 'string',
'vendorpartnumber' => 'string',
'upc' => 'string',
'customerpartnumber' => 'string',
'warehouseidlist' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'index' => null,
'ingrampartnumber' => null,
'vendorpartnumber' => null,
'upc' => null,
'customerpartnumber' => null,
'warehouseidlist' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'index' => 'index',
'ingrampartnumber' => 'ingrampartnumber',
'vendorpartnumber' => 'vendorpartnumber',
'upc' => 'UPC',
'customerpartnumber' => 'customerpartnumber',
'warehouseidlist' => 'warehouseidlist'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'index' => 'setIndex',
'ingrampartnumber' => 'setIngrampartnumber',
'vendorpartnumber' => 'setVendorpartnumber',
'upc' => 'setUpc',
'customerpartnumber' => 'setCustomerpartnumber',
'warehouseidlist' => 'setWarehouseidlist'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'index' => 'getIndex',
'ingrampartnumber' => 'getIngrampartnumber',
'vendorpartnumber' => 'getVendorpartnumber',
'upc' => 'getUpc',
'customerpartnumber' => 'getCustomerpartnumber',
'warehouseidlist' => 'getWarehouseidlist'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['index'] = isset($data['index']) ? $data['index'] : null;
        $this->container['ingrampartnumber'] = isset($data['ingrampartnumber']) ? $data['ingrampartnumber'] : null;
        $this->container['vendorpartnumber'] = isset($data['vendorpartnumber']) ? $data['vendorpartnumber'] : null;
        $this->container['upc'] = isset($data['upc']) ? $data['upc'] : null;
        $this->container['customerpartnumber'] = isset($data['customerpartnumber']) ? $data['customerpartnumber'] : null;
        $this->container['warehouseidlist'] = isset($data['warehouseidlist']) ? $data['warehouseidlist'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets index
     *
     * @return int
     */
    public function getIndex()
    {
        return $this->container['index'];
    }

    /**
     * Sets index
     *
     * @param int $index index
     *
     * @return $this
     */
    public function setIndex($index)
    {
        $this->container['index'] = $index;

        return $this;
    }

    /**
     * Gets ingrampartnumber
     *
     * @return string
     */
    public function getIngrampartnumber()
    {
        return $this->container['ingrampartnumber'];
    }

    /**
     * Sets ingrampartnumber
     *
     * @param string $ingrampartnumber Ingram Micro system specific SKU number for the product for which the price is requested at Ingram Micro
     *
     * @return $this
     */
    public function setIngrampartnumber($ingrampartnumber)
    {
        $this->container['ingrampartnumber'] = $ingrampartnumber;

        return $this;
    }

    /**
     * Gets vendorpartnumber
     *
     * @return string
     */
    public function getVendorpartnumber()
    {
        return $this->container['vendorpartnumber'];
    }

    /**
     * Sets vendorpartnumber
     *
     * @param string $vendorpartnumber Vendor Part Number for the product for which the price is requested at Ingram Micro
     *
     * @return $this
     */
    public function setVendorpartnumber($vendorpartnumber)
    {
        $this->container['vendorpartnumber'] = $vendorpartnumber;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string
     */
    public function getUpc()
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string $upc Universal Product code for the product for which the price is requested at Ingram Micro
     *
     * @return $this
     */
    public function setUpc($upc)
    {
        $this->container['upc'] = $upc;

        return $this;
    }

    /**
     * Gets customerpartnumber
     *
     * @return string
     */
    public function getCustomerpartnumber()
    {
        return $this->container['customerpartnumber'];
    }

    /**
     * Sets customerpartnumber
     *
     * @param string $customerpartnumber Unique identification number of customer. For this option the Ingram Micro Sales rep must set up a cross reference table.
     *
     * @return $this
     */
    public function setCustomerpartnumber($customerpartnumber)
    {
        $this->container['customerpartnumber'] = $customerpartnumber;

        return $this;
    }

    /**
     * Gets warehouseidlist
     *
     * @return string
     */
    public function getWarehouseidlist()
    {
        return $this->container['warehouseidlist'];
    }

    /**
     * Sets warehouseidlist
     *
     * @param string $warehouseidlist Unique identity for Ingram Micro warehouses against which stock details are returned.
     *
     * @return $this
     */
    public function setWarehouseidlist($warehouseidlist)
    {
        $this->container['warehouseidlist'] = $warehouseidlist;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
