<?php
/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsProductextendedspecs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsProductextendedspecs Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsProductextendedspecs implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderCreate_v4_0_vse0_ordercreaterequest_ordercreatedetails_productextendedspecs';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'attributename' => 'string',
'attributevalue' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'attributename' => null,
'attributevalue' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attributename' => 'attributename',
'attributevalue' => 'attributevalue'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attributename' => 'setAttributename',
'attributevalue' => 'setAttributevalue'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attributename' => 'getAttributename',
'attributevalue' => 'getAttributevalue'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ATTRIBUTENAME_SHIPFROM = 'shipfrom';
const ATTRIBUTENAME_SPECIALPRICE = 'specialprice';
const ATTRIBUTENAME_AUTHBIDNUMBER = 'authbidnumber';
const ATTRIBUTENAME_COMMENTTEXT = 'commenttext';
const ATTRIBUTENAME_SERIALNUMBER = 'serialnumber';
const ATTRIBUTENAME_CONTACTNUMBER = 'contactnumber';
const ATTRIBUTENAME_SHIPNOTESTXT = 'shipnotestxt';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAttributenameAllowableValues()
    {
        return [
            self::ATTRIBUTENAME_SHIPFROM,
self::ATTRIBUTENAME_SPECIALPRICE,
self::ATTRIBUTENAME_AUTHBIDNUMBER,
self::ATTRIBUTENAME_COMMENTTEXT,
self::ATTRIBUTENAME_SERIALNUMBER,
self::ATTRIBUTENAME_CONTACTNUMBER,
self::ATTRIBUTENAME_SHIPNOTESTXT,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['attributename'] = isset($data['attributename']) ? $data['attributename'] : null;
        $this->container['attributevalue'] = isset($data['attributevalue']) ? $data['attributevalue'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAttributenameAllowableValues();
        if (!is_null($this->container['attributename']) && !in_array($this->container['attributename'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'attributename', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attributename
     *
     * @return string
     */
    public function getAttributename()
    {
        return $this->container['attributename'];
    }

    /**
     * Sets attributename
     *
     * @param string $attributename attributename
     *
     * @return $this
     */
    public function setAttributename($attributename)
    {
        $allowedValues = $this->getAttributenameAllowableValues();
        if (!is_null($attributename) && !in_array($attributename, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'attributename', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['attributename'] = $attributename;

        return $this;
    }

    /**
     * Gets attributevalue
     *
     * @return string
     */
    public function getAttributevalue()
    {
        return $this->container['attributevalue'];
    }

    /**
     * Sets attributevalue
     *
     * @param string $attributevalue attributevalue
     *
     * @return $this
     */
    public function setAttributevalue($attributevalue)
    {
        $this->container['attributevalue'] = $attributevalue;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
