<?php
/**
 * InvoiceDetailResponseServiceresponseInvoicedetailresponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceDetailResponseServiceresponseInvoicedetailresponseTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceDetailResponseServiceresponseInvoicedetailresponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceDetailResponseServiceresponseInvoicedetailresponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceDetailResponseServiceresponseInvoicedetailresponse"
     */
    public function testInvoiceDetailResponseServiceresponseInvoicedetailresponse()
    {
    }

    /**
     * Test attribute "customernumber"
     */
    public function testPropertyCustomernumber()
    {
    }

    /**
     * Test attribute "invoicenumber"
     */
    public function testPropertyInvoicenumber()
    {
    }

    /**
     * Test attribute "invoicedate"
     */
    public function testPropertyInvoicedate()
    {
    }

    /**
     * Test attribute "invoicetype"
     */
    public function testPropertyInvoicetype()
    {
    }

    /**
     * Test attribute "customerordernumber"
     */
    public function testPropertyCustomerordernumber()
    {
    }

    /**
     * Test attribute "customerfreightamount"
     */
    public function testPropertyCustomerfreightamount()
    {
    }

    /**
     * Test attribute "customerforeignfrightamt"
     */
    public function testPropertyCustomerforeignfrightamt()
    {
    }

    /**
     * Test attribute "totaltaxamount"
     */
    public function testPropertyTotaltaxamount()
    {
    }

    /**
     * Test attribute "totalamount"
     */
    public function testPropertyTotalamount()
    {
    }

    /**
     * Test attribute "shiptosuffix"
     */
    public function testPropertyShiptosuffix()
    {
    }

    /**
     * Test attribute "billtosuffix"
     */
    public function testPropertyBilltosuffix()
    {
    }

    /**
     * Test attribute "freightamount"
     */
    public function testPropertyFreightamount()
    {
    }

    /**
     * Test attribute "paymentterms"
     */
    public function testPropertyPaymentterms()
    {
    }

    /**
     * Test attribute "orderdate"
     */
    public function testPropertyOrderdate()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "carrierdescription"
     */
    public function testPropertyCarrierdescription()
    {
    }

    /**
     * Test attribute "discountamount"
     */
    public function testPropertyDiscountamount()
    {
    }

    /**
     * Test attribute "taxtype"
     */
    public function testPropertyTaxtype()
    {
    }

    /**
     * Test attribute "enduserponumber"
     */
    public function testPropertyEnduserponumber()
    {
    }

    /**
     * Test attribute "freightforwardercode"
     */
    public function testPropertyFreightforwardercode()
    {
    }

    /**
     * Test attribute "creditmemoreasoncode"
     */
    public function testPropertyCreditmemoreasoncode()
    {
    }
}
