<?php
/**
 * MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItemTest Class Doc Comment
 *
 * @category    Class
 * @description MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItem"
     */
    public function testMultiSKUPriceAndStockAPIV40ServiceVs0ServicerequestPriceandstockrequestItem()
    {
    }

    /**
     * Test attribute "index"
     */
    public function testPropertyIndex()
    {
    }

    /**
     * Test attribute "ingrampartnumber"
     */
    public function testPropertyIngrampartnumber()
    {
    }

    /**
     * Test attribute "vendorpartnumber"
     */
    public function testPropertyVendorpartnumber()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "customerpartnumber"
     */
    public function testPropertyCustomerpartnumber()
    {
    }

    /**
     * Test attribute "warehouseidlist"
     */
    public function testPropertyWarehouseidlist()
    {
    }
}
