<?php
/**
 * MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseWarehousedetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseWarehousedetailsTest Class Doc Comment
 *
 * @category    Class
 * @description MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseWarehousedetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseWarehousedetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseWarehousedetails"
     */
    public function testMultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseWarehousedetails()
    {
    }

    /**
     * Test attribute "warehouseid"
     */
    public function testPropertyWarehouseid()
    {
    }

    /**
     * Test attribute "warehousedescription"
     */
    public function testPropertyWarehousedescription()
    {
    }

    /**
     * Test attribute "availablequantity"
     */
    public function testPropertyAvailablequantity()
    {
    }

    /**
     * Test attribute "onorderquantity"
     */
    public function testPropertyOnorderquantity()
    {
    }

    /**
     * Test attribute "onholdquantity"
     */
    public function testPropertyOnholdquantity()
    {
    }

    /**
     * Test attribute "etadate"
     */
    public function testPropertyEtadate()
    {
    }
}
