<?php
/**
 * MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseDetails"
     */
    public function testMultiSKUPriceAndStockResponseServiceresponsePriceandstockresponseDetails()
    {
    }

    /**
     * Test attribute "itemstatus"
     */
    public function testPropertyItemstatus()
    {
    }

    /**
     * Test attribute "statusmessage"
     */
    public function testPropertyStatusmessage()
    {
    }

    /**
     * Test attribute "ingrampartnumber"
     */
    public function testPropertyIngrampartnumber()
    {
    }

    /**
     * Test attribute "vendorpartnumber"
     */
    public function testPropertyVendorpartnumber()
    {
    }

    /**
     * Test attribute "globalskuid"
     */
    public function testPropertyGlobalskuid()
    {
    }

    /**
     * Test attribute "customerprice"
     */
    public function testPropertyCustomerprice()
    {
    }

    /**
     * Test attribute "partdescription1"
     */
    public function testPropertyPartdescription1()
    {
    }

    /**
     * Test attribute "partdescription2"
     */
    public function testPropertyPartdescription2()
    {
    }

    /**
     * Test attribute "vendornumber"
     */
    public function testPropertyVendornumber()
    {
    }

    /**
     * Test attribute "vendorname"
     */
    public function testPropertyVendorname()
    {
    }

    /**
     * Test attribute "cpucode"
     */
    public function testPropertyCpucode()
    {
    }

    /**
     * Test attribute "class"
     */
    public function testPropertyClass()
    {
    }

    /**
     * Test attribute "skustatus"
     */
    public function testPropertySkustatus()
    {
    }

    /**
     * Test attribute "mediacpu"
     */
    public function testPropertyMediacpu()
    {
    }

    /**
     * Test attribute "categorysubcategory"
     */
    public function testPropertyCategorysubcategory()
    {
    }

    /**
     * Test attribute "retailprice"
     */
    public function testPropertyRetailprice()
    {
    }

    /**
     * Test attribute "newmedia"
     */
    public function testPropertyNewmedia()
    {
    }

    /**
     * Test attribute "enduserrequired"
     */
    public function testPropertyEnduserrequired()
    {
    }

    /**
     * Test attribute "backorderflag"
     */
    public function testPropertyBackorderflag()
    {
    }

    /**
     * Test attribute "skuauthorized"
     */
    public function testPropertySkuauthorized()
    {
    }

    /**
     * Test attribute "extendedvendorpartnumber"
     */
    public function testPropertyExtendedvendorpartnumber()
    {
    }

    /**
     * Test attribute "warehousedetails"
     */
    public function testPropertyWarehousedetails()
    {
    }
}
