<?php
/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsTest Class Doc Comment
 *
 * @category    Class
 * @description OrderCreateV40Vse0OrdercreaterequestOrdercreatedetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderCreateV40Vse0OrdercreaterequestOrdercreatedetails"
     */
    public function testOrderCreateV40Vse0OrdercreaterequestOrdercreatedetails()
    {
    }

    /**
     * Test attribute "customerponumber"
     */
    public function testPropertyCustomerponumber()
    {
    }

    /**
     * Test attribute "ordertype"
     */
    public function testPropertyOrdertype()
    {
    }

    /**
     * Test attribute "enduserordernumber"
     */
    public function testPropertyEnduserordernumber()
    {
    }

    /**
     * Test attribute "billtosuffix"
     */
    public function testPropertyBilltosuffix()
    {
    }

    /**
     * Test attribute "shiptosuffix"
     */
    public function testPropertyShiptosuffix()
    {
    }

    /**
     * Test attribute "shiptoaddress"
     */
    public function testPropertyShiptoaddress()
    {
    }

    /**
     * Test attribute "carriercode"
     */
    public function testPropertyCarriercode()
    {
    }

    /**
     * Test attribute "thirdpartyfrieghtaccountnumber"
     */
    public function testPropertyThirdpartyfrieghtaccountnumber()
    {
    }

    /**
     * Test attribute "specialbidnumber"
     */
    public function testPropertySpecialbidnumber()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "extendedspecs"
     */
    public function testPropertyExtendedspecs()
    {
    }
}
