<?php
/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsLinesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsLinesTest Class Doc Comment
 *
 * @category    Class
 * @description OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsLines
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsLinesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsLines"
     */
    public function testOrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsLines()
    {
    }

    /**
     * Test attribute "linetype"
     */
    public function testPropertyLinetype()
    {
    }

    /**
     * Test attribute "linenumber"
     */
    public function testPropertyLinenumber()
    {
    }

    /**
     * Test attribute "ingrampartnumber"
     */
    public function testPropertyIngrampartnumber()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "vendorpartnumber"
     */
    public function testPropertyVendorpartnumber()
    {
    }

    /**
     * Test attribute "customerpartnumber"
     */
    public function testPropertyCustomerpartnumber()
    {
    }

    /**
     * Test attribute "upc_code"
     */
    public function testPropertyUpcCode()
    {
    }

    /**
     * Test attribute "warehouseid"
     */
    public function testPropertyWarehouseid()
    {
    }

    /**
     * Test attribute "unitprice"
     */
    public function testPropertyUnitprice()
    {
    }

    /**
     * Test attribute "enduser"
     */
    public function testPropertyEnduser()
    {
    }

    /**
     * Test attribute "productextendedspecs"
     */
    public function testPropertyProductextendedspecs()
    {
    }
}
