<?php
/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsEnduserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ingram Micro eCommerce APIs
 *
 * Ingram Micro API collection for automating eCommerce business processes including orering and product search.
 *
 * OpenAPI spec version: 1.0
 * Contact: apiportalsupport@ingrammicro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsEnduserTest Class Doc Comment
 *
 * @category    Class
 * @description OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsEnduser
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsEnduserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsEnduser"
     */
    public function testOrderCreateV40Vse0OrdercreaterequestOrdercreatedetailsEnduser()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "addressline1"
     */
    public function testPropertyAddressline1()
    {
    }

    /**
     * Test attribute "addressline2"
     */
    public function testPropertyAddressline2()
    {
    }

    /**
     * Test attribute "addressline3"
     */
    public function testPropertyAddressline3()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "postalcode"
     */
    public function testPropertyPostalcode()
    {
    }

    /**
     * Test attribute "countrycode"
     */
    public function testPropertyCountrycode()
    {
    }

    /**
     * Test attribute "phonenumber"
     */
    public function testPropertyPhonenumber()
    {
    }

    /**
     * Test attribute "extensionnumber"
     */
    public function testPropertyExtensionnumber()
    {
    }

    /**
     * Test attribute "faxnumber"
     */
    public function testPropertyFaxnumber()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }
}
